#!/usr/bin/env bash

source sb-colour-scheme
base=$col_white
col_battery_full=$col_pink
col_battery_discharging=$col_pink
col_battery_charging=$col_pink
col_battery_not_charging=$col_red
col_battery_unknown=$col_white

# https://github.com/LukeSmithxyz/voidrice/tree/master/.local/bin/statusbar
# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status ( for plugged in, 󰁿 for discharging on battery, etc.).

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
# If non-first battery, print a space separator.
[ -n "${val_battery+x}" ] && printf " "
# Sets up the status and capacity
case "$(cat "$battery/status" 2>&1)" in
  "Full") status="^c$col_battery_full^󰂄" ;;
  "Discharging") status="^c$col_battery_discharging^󰁿" ;;
  "Charging") status="^c$col_battery_charging^󰚥" ;;
  "Not charging") status="^c$col_battery_not_charging^󰅜" ;;
  "Unknown") status="^c$col_battery_unknown^󰋗" ;;
  *) exit 1 ;;
esac

val_battery="$(cat "$battery/capacity" 2>&1)"
# Will set variable to warn if discharging and low
[ "$status" = "^c$yellow^󰁿" ] && [ "$val_battery" -le 25 ] && status="^c$col_battery_low_warning^󰂃"
# Prints the info
printf "^c$base^%s ^c$base^%s%%" "$status" "$val_battery"
done && printf "\\n"