#!/usr/bin/env bash

source sb-colour-scheme
base=$col_white
col_volume_high=$col_lavender
col_volume_medium=$col_lavender
col_volume_low=$col_lavender
col_volume_mute=$col_red
col_volume_unknown=$col_white

# https://github.com/LukeSmithxyz/voidrice/tree/master/.local/bin/statusbar
# Prints the current volume or 󰖁 if muted.

if [[ "$(pamixer --get-mute)" = "true" ]]; then
# $(amixer sget master | awk -f\"[][]\" '/%/' | head -n1 | awk '{print $6}')" = "[off]"
  icon="󰖁"
  printf "^c$col_volume_mute^%s" "$icon"
else
  val_volume="$(pamixer --get-volume)"  
# "$(amixer sget Master | awk -F\"[][]\" '/%/' | head -n1 | awk '{print $5}' | sed 's/[[]//g' | sed 's/%]//g')"  

  if [[ "$val_volume" -gt "70" ]]; then 
    icon="^c$col_volume_high^󰕾";
  elif [[ "$val_volume" -gt "30" ]]; then 
    icon="^c$col_volume_medium^󰖀";
  elif [[ "$val_volume" -gt "0" ]]; then 
    icon="^c$col_volume_low^󰕿";
  else 
    icon="^c$col_volume_unknown^󰋗";
  fi

  printf "^c$base^%s ^c$base^%s%%" "$icon" "$val_volume"
fi